# Generated by Django 3.1.2 on 2020-10-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='CreatedDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
