# Generated by Django 3.1.2 on 2020-10-08 16:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0006_auto_20201008_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_users',
            field=models.ManyToManyField(through='Users.ProjectUserRelation', to=settings.AUTH_USER_MODEL),
        ),
    ]
