# Generated by Django 3.1.2 on 2020-10-08 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0008_auto_20201008_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectuserrelation',
            name='project_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.projects'),
        ),
        migrations.AlterField(
            model_name='projectuserrelation',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
