# Generated by Django 3.1.2 on 2020-10-08 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_remove_tickets_submitter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='project',
            new_name='projects',
        ),
    ]
