# Generated by Django 3.1.2 on 2020-10-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_auto_20201008_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='priority',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Closed', 'Closed')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='type',
            field=models.CharField(blank=True, choices=[('Feature/Request', 'Feature/Request'), ('Bug/Error', 'Bug/Error'), ('Others', 'Others')], max_length=20, null=True),
        ),
    ]
