# Generated by Django 3.1.2 on 2020-10-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0013_auto_20201009_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
