# Generated by Django 3.1.2 on 2020-10-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0015_auto_20201010_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='ticket_form_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
